language: android

env:
  global:
    - GRADLE_OPTS=-Xmx512m

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew assemble anvil:check --stacktrace
